In [5]:
import numpy as np


In [7]:
ary=np.array([10,20,30,40,50])

In [8]:
ary

array([10, 20, 30, 40, 50])

In [11]:
a=[[10,20,30,40],[50,60,70,80],[100,200,300,400]]
a=np.array(a)

In [12]:
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [100, 200, 300, 400]])

In [13]:
a.shape

(3, 4)

In [14]:
a.itemsize

8

In [15]:
a.itemsize*a.size

96

In [17]:
z1=np.zeros((4,6))

In [18]:
z1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
z1.shape

(4, 6)

In [20]:
z1.ndim

2

In [27]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#sum of elements
np.sum(arr)

np.int64(45)

In [29]:
#mean of elements
np.mean(arr)

np.float64(5.0)

In [30]:
#reshaping of array
arr2=np.reshape(arr,(3,3))
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#broadcasting function
arr3=np.array([10,20,30,40,50,60,70,80,90])
arr3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
arr_broad=arr+arr3

In [34]:
arr_broad

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [35]:
#vectorized multiplication
np.multiply(arr,arr3)

array([ 10,  40,  90, 160, 250, 360, 490, 640, 810])

In [36]:
#vectorized multiplication
np.multiply(arr,arr_broad)

array([ 11,  44,  99, 176, 275, 396, 539, 704, 891])

In [42]:
#random number generating function
random_arr=np.random.rand(10)
print('random array',random_arr)

random array [0.2947353  0.11723419 0.01978037 0.16871699 0.68334848 0.6286498
 0.56781766 0.65907711 0.07448358 0.35070669]
