In [5]:
import numpy as np


In [7]:
ary=np.array([10,20,30,40,50])

In [8]:
ary

array([10, 20, 30, 40, 50])

In [11]:
a=[[10,20,30,40],[50,60,70,80],[100,200,300,400]]
a=np.array(a)

In [12]:
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [100, 200, 300, 400]])

In [13]:
a.shape

(3, 4)

In [14]:
a.itemsize

8

In [15]:
a.itemsize*a.size

96

In [17]:
z1=np.zeros((4,6))

In [18]:
z1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
z1.shape

(4, 6)

In [20]:
z1.ndim

2

In [27]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#sum of elements
np.sum(arr)

np.int64(45)

In [29]:
#mean of elements
np.mean(arr)

np.float64(5.0)

In [30]:
#reshaping of array
arr2=np.reshape(arr,(3,3))
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#broadcasting function
arr3=np.array([10,20,30,40,50,60,70,80,90])
arr3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
arr_broad=arr+arr3

In [34]:
arr_broad

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [35]:
#vectorized multiplication
np.multiply(arr,arr3)

array([ 10,  40,  90, 160, 250, 360, 490, 640, 810])

In [36]:
#vectorized multiplication
np.multiply(arr,arr_broad)

array([ 11,  44,  99, 176, 275, 396, 539, 704, 891])

In [42]:
#random number generating function
random_arr=np.random.rand(10)
print('random array',random_arr)

random array [0.2947353  0.11723419 0.01978037 0.16871699 0.68334848 0.6286498
 0.56781766 0.65907711 0.07448358 0.35070669]


In [43]:
import numpy as np
ary=np.array([12,20,30,40,50])

In [45]:
print(ary),type(ary)

[12 20 30 40 50]


(None, numpy.ndarray)

In [46]:
ary.ndim

1

In [47]:
ary.size

5

In [48]:
nlist=[10,20,30,40,50]

In [49]:
type(nlist)

list

In [50]:
print(nlist)

[10, 20, 30, 40, 50]


In [51]:
len(nlist)

5

In [52]:
ary.itemsize

8

In [53]:
ary.dtype

dtype('int64')

In [56]:
a=[[10,20,30,40],[50,60,70,80],[100,200,300,400]]
ary2=np.array(a)

In [57]:
ary2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [100, 200, 300, 400]])

In [58]:
ary2.shape

(3, 4)

In [59]:
ary2.size

12

In [60]:
ary.itemsize

8

In [61]:
ary2.itemsize*ary2.size

96

In [71]:
z1=np.zeros((5,6))

In [72]:
z1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [73]:
type(z1)

numpy.ndarray

In [74]:
z1.shape

(5, 6)

In [75]:
z1.ndim

2

In [76]:
z1.size

30

In [77]:
z1.dtype

dtype('float64')

In [78]:
z1.itemsize

8

In [79]:
np.zeros((2,4,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [91]:
import numpy as np
a1=np.random.randint(10,40,(10))

In [92]:
a1

array([34, 35, 29, 23, 33, 38, 35, 35, 32, 18], dtype=int32)

In [94]:
#Indexing
a1[4]
print(a1[4])

33


In [95]:
a1[-6]
print(a1[-6])

33


In [96]:
#Slicing
a1[1:8:1]

array([35, 29, 23, 33, 38, 35, 35], dtype=int32)

In [97]:
a2=np.random.randint(10,40,(4,6))

In [98]:
a2

array([[35, 18, 12, 24, 21, 30],
       [17, 36, 32, 14, 27, 14],
       [28, 28, 37, 22, 35, 13],
       [13, 10, 25, 22, 29, 11]], dtype=int32)

In [100]:
a2.shape

(4, 6)

In [101]:
a2[1][4]

np.int32(27)

In [102]:
a2[3][1]

np.int32(10)

In [103]:
a2[3][5]

np.int32(11)

In [104]:
a2[3][3]

np.int32(22)

In [106]:
a2[1:5:1,2:6:1]

array([[32, 14, 27, 14],
       [37, 22, 35, 13],
       [25, 22, 29, 11]], dtype=int32)

In [107]:
a2[2:6:1]

array([[28, 28, 37, 22, 35, 13],
       [13, 10, 25, 22, 29, 11]], dtype=int32)

In [108]:
a1=np.random.randint(20,80,(20))
a1

array([71, 62, 52, 39, 47, 52, 31, 73, 49, 51, 55, 72, 30, 50, 58, 35, 26,
       74, 41, 72], dtype=int32)

In [109]:
a1>50

array([ True,  True,  True, False, False,  True, False,  True, False,
        True,  True,  True, False, False,  True, False, False,  True,
       False,  True])

In [110]:
a1[a1>50]

array([71, 62, 52, 52, 73, 51, 55, 72, 58, 74, 72], dtype=int32)

In [111]:
ary=np.random.randint(10,40,(3,5))

In [112]:
ary

array([[23, 27, 22, 37, 12],
       [28, 29, 13, 32, 23],
       [29, 38, 35, 37, 27]], dtype=int32)

In [113]:
ary.shape


(3, 5)

In [115]:
ary.transpose()

array([[23, 28, 29],
       [27, 29, 38],
       [22, 13, 35],
       [37, 32, 37],
       [12, 23, 27]], dtype=int32)